# todo bill_details_iterator
#   function shall take a DataFrame generated by BillsOverview and yield the details for each bill in series
#   it shall call get_summary(path), get_votes(bill_name) for each item in the DataFrame
from parlpy.bills.bill_list_fetcher import BillsOverview

def get_bill_details(overview: BillsOverview):
