"""
Robert Chambers 2021
"""
# todo: new module called bill_details_iterator
#   function shall take a DataFrame generated by BillsOverview and yield the details for each bill in series
#   it shall call get_summary(path), get_votes(bill_name) for each item in the DataFrame


def fetch_votes(bill_title: str):
    pass